version: '3.3'

services:
  odinium-prod-wordpress-mysql:
    container_name: odinium-prod-wordpress-mysql
    image: mysql:5.7
    volumes:
      - ./mysql/mysql-setup.sql:/docker-entrypoint-initdb.d/init.sql
      - ./build/var/lib/mysql-odinium-prod:/var/lib/mysql
    restart: always
    ports:
      - "3316:3306"
    environment:
      MYSQL_ROOT_PASSWORD: localhost
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: localhost

  odinium-prod-wordpress:
    container_name: odinium-prod-wordpress
    depends_on:
      - odinium-prod-wordpress-mysql
    image: wordpress:latest
    ports:
      - "8016:80"
    volumes:
      - ./build/var/www/html-odinium-prod:/var/www/html
    restart: always
    links:
      - odinium-prod-wordpress-mysql
    environment:
      WORDPRESS_DB_HOST: odinium-prod-wordpress-mysql
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: localhost
