apiVersion: v1
kind: Service
metadata:
  name: neo4k-springboot-service
spec:
  type: NodePort
  ports:
    - targetPort: 5000
      port: 5000
      nodePort: 30010
  selector:
    app: neo4k-springboot

